import { GraphIR } from '../../types/braid';

export function generateOpenServTypeScriptSdk(
  graph: GraphIR,
  agentName: string = 'KumivyrAgent',
  mermaidCode: string
): string {
  const cleanName = agentName.replace(/[^a-zA-Z0-9]/g, '');
  const capabilities: string[] = [];

  // Generate capability for each action or high-stakes node
  graph.nodes.forEach((node) => {
    if (node.type === 'action' || node.type === 'decision') {
      const capName = node.label.toLowerCase().replace(/[^a-z0-9]/g, '_').slice(0, 32);
      capabilities.push(`
  // Capability: ${node.label}
  agent.addCapability({
    name: '${capName}',
    description: 'Autonomous reasoning step: ${node.label}',
    inputSchema: z.object({
      payload: z.record(z.any()).describe('Current execution payload variables'),
      strictness: z.enum(['permissive', 'balanced', 'strict']).default('strict'),
    }),
    async run({ args }) {
      // Bounded node execution guarded by Kumivyr reasoning graph
      return {
        nodeId: '${node.id}',
        status: 'SUCCESS',
        executedAt: new Date().toISOString(),
        data: args.payload,
      };
    },
  });`);
    }
  });

  return `/**
 * Generated by Kumivyr • The BRAID Reasoning Workbench for OpenServ
 * Target Framework: @openserv-labs/sdk (v2.x)
 * Model: gpt-5.4-nano-multipath
 */

import { Agent, run } from '@openserv-labs/sdk';
import { z } from 'zod';
import dotenv from 'dotenv';

dotenv.config();

// 1. Initialize OpenServ Agent with compiled Guided Reasoning Diagram (GRD)
export const agent = new Agent({
  systemPrompt: \`You are an autonomous agent powered by OpenServ BRAID Reasoning.
Execute the following machine-native Guided Reasoning Diagram node by node without drift:

\\\`\\\`\\\`mermaid
${mermaidCode.trim()}
\\\`\\\`\\\`
\`,
  apiKey: process.env.OPENSERV_API_KEY,
});

// 2. Register Bounded Capabilities
${capabilities.join('\n')}

// 3. Local Development Runner with WebSocket Tunnel
async function main() {
  console.log('🚀 Launching ${cleanName} on OpenServ platform...');
  const { stop } = await run(agent);

  process.on('SIGINT', async () => {
    console.log('Shutting down agent tunnel...');
    await stop();
    process.exit(0);
  });
}

if (import.meta.url === \`file://\${process.argv[1]}\`) {
  main().catch(console.error);
}
`;
}

export function generatePythonSdkAgent(
  graph: GraphIR,
  agentName: string = 'KumivyrAgent',
  mermaidCode: string
): string {
  return `"""
Generated by Kumivyr • The BRAID Reasoning Workbench for OpenServ
Target Framework: openserv-labs/python-sdk
"""

import os
from openserv import Agent, Capability
from pydantic import BaseModel, Field

SYSTEM_PROMPT = """You are an autonomous agent powered by OpenServ BRAID Reasoning.
Execute the following machine-native Guided Reasoning Diagram node by node:

\`\`\`mermaid
${mermaidCode.trim()}
\`\`\`
"""

agent = Agent(
    name="${agentName}",
    system_prompt=SYSTEM_PROMPT,
    api_key=os.getenv("OPENSERV_API_KEY")
)

@agent.capability(name="verify_and_execute")
def handle_execution(payload: dict):
    # Node-by-node execution following the BRAID flowchart
    return {"status": "SUCCESS", "node_count": ${graph.metrics.nodeCount}}

if __name__ == "__main__":
    agent.run()
`;
}
